default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV['RAILS_MAX_THREADS'] || 2 %>
  database: launchpad

development:
  <<: *default
  username: root
  password: root

test:
  <<: *default
  username: root
  password: root
  
production:
  <<: *default

